//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	/// <summary>
	/// DomainRelationship ExampleModelHasElements
	/// Embedding relationship between the Model and Elements
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("cbb2df1d-4cae-46bb-aa29-44c9d48dca4d")]
	public partial class ExampleModelHasElements : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// ExampleModelHasElements domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xcbb2df1d, 0x4cae, 0x46bb, 0xaa, 0x29, 0x44, 0xc9, 0xd4, 0x8d, 0xca, 0x4d);
	
				
		/// <summary>
		/// Constructor
		/// Creates a ExampleModelHasElements link in the same Partition as the given ExampleModel
		/// </summary>
		/// <param name="source">ExampleModel to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public ExampleModelHasElements(ExampleModel source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(ExampleModelHasElements.ExampleModelDomainRoleId, source), new DslModeling::RoleAssignment(ExampleModelHasElements.ElementDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasElements(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasElements(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public ExampleModelHasElements(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public ExampleModelHasElements(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region ExampleModel domain role code
		
		/// <summary>
		/// ExampleModel domain role Id.
		/// </summary>
		public static readonly global::System.Guid ExampleModelDomainRoleId = new global::System.Guid(0xff786e02, 0x220d, 0x459b, 0x8f, 0xca, 0x95, 0x1e, 0x9e, 0x4f, 0xf9, 0x46);
		
		/// <summary>
		/// DomainRole ExampleModel
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements/ExampleModel.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements/ExampleModel.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Elements", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements/ExampleModel.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("ff786e02-220d-459b-8fca-951e9e4ff946")]
		public virtual ExampleModel ExampleModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (ExampleModel)DslModeling::DomainRoleInfo.GetRolePlayer(this, ExampleModelDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ExampleModelDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access ExampleModel of a Entidad
		/// <summary>
		/// Gets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static ExampleModel GetExampleModel(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ElementDomainRoleId) as ExampleModel;
		}
		
		/// <summary>
		/// Sets ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetExampleModel(Entidad element, ExampleModel newExampleModel)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ElementDomainRoleId, newExampleModel);
		}
		#endregion
		#region Element domain role code
		
		/// <summary>
		/// Element domain role Id.
		/// </summary>
		public static readonly global::System.Guid ElementDomainRoleId = new global::System.Guid(0xa386d193, 0x61de, 0x45ea, 0xa5, 0x0f, 0xd2, 0x8a, 0x64, 0x41, 0xcd, 0x51);
		
		/// <summary>
		/// DomainRole Element
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements/Element.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements/Element.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "ExampleModel", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements/Element.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("a386d193-61de-45ea-a50f-d28a6441cd51")]
		public virtual Entidad Element
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, ElementDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ElementDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Elements of a ExampleModel
		/// <summary>
		/// Gets a list of Elements.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetElements(ExampleModel element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, ExampleModelDomainRoleId);
		}
		#endregion
		#region ExampleModel link accessor
		/// <summary>
		/// Get the list of ExampleModelHasElements links to a ExampleModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements> GetLinksToElements ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModel exampleModelInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements>(exampleModelInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements.ExampleModelDomainRoleId);
		}
		#endregion
		#region Element link accessor
		/// <summary>
		/// Get the ExampleModelHasElements link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements GetLinkToExampleModel (global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad elementInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements>(elementInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements.ElementDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Element not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region ExampleModelHasElements instance accessors
		
		/// <summary>
		/// Get any ExampleModelHasElements links between a given ExampleModel and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements> GetLinks( global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModel source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements>();
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements.ExampleModelDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one ExampleModelHasElements link between a given ExampleModeland a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements GetLink( global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModel source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements.ExampleModelDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	/// <summary>
	/// DomainRelationship EntidadReferencesTargets
	/// Reference relationship between Elements.
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("2dff95dc-b82d-476b-aa6d-9294349806cf")]
	public partial class EntidadReferencesTargets : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadReferencesTargets domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x2dff95dc, 0xb82d, 0x476b, 0xaa, 0x6d, 0x92, 0x94, 0x34, 0x98, 0x06, 0xcf);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadReferencesTargets link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public EntidadReferencesTargets(Entidad source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadReferencesTargets.SourceDomainRoleId, source), new DslModeling::RoleAssignment(EntidadReferencesTargets.TargetDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesTargets(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesTargets(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferencesTargets(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferencesTargets(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Source domain role code
		
		/// <summary>
		/// Source domain role Id.
		/// </summary>
		public static readonly global::System.Guid SourceDomainRoleId = new global::System.Guid(0xda2ea47d, 0x75ab, 0x403f, 0xb1, 0x76, 0xed, 0x16, 0xd6, 0xae, 0xf7, 0x3f);
		
		/// <summary>
		/// DomainRole Source
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleRelationship.Target
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets/Source.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets/Source.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Targets", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets/Source.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("da2ea47d-75ab-403f-b176-ed16d6aef73f")]
		public virtual Entidad Source
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, SourceDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, SourceDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Sources of a Entidad
		/// <summary>
		/// Gets a list of Sources.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetSources(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, TargetDomainRoleId);
		}
		#endregion
		#region Target domain role code
		
		/// <summary>
		/// Target domain role Id.
		/// </summary>
		public static readonly global::System.Guid TargetDomainRoleId = new global::System.Guid(0x6727d531, 0x64e8, 0x432a, 0xbf, 0x9e, 0x62, 0xc2, 0x4a, 0xa4, 0x7b, 0xda);
		
		/// <summary>
		/// DomainRole Target
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.ExampleRelationship.Source
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets/Target.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets/Target.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Sources", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets/Target.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("6727d531-64e8-432a-bf9e-62c24aa47bda")]
		public virtual Entidad Target
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, TargetDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TargetDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Targets of a Entidad
		/// <summary>
		/// Gets a list of Targets.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetTargets(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, SourceDomainRoleId);
		}
		#endregion
		#region Source link accessor
		/// <summary>
		/// Get the list of EntidadReferencesTargets links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets> GetLinksToTargets ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad sourceInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets>(sourceInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets.SourceDomainRoleId);
		}
		#endregion
		#region Target link accessor
		/// <summary>
		/// Get the list of EntidadReferencesTargets links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets> GetLinksToSources ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad targetInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets>(targetInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets.TargetDomainRoleId);
		}
		#endregion
		#region EntidadReferencesTargets instance accessors
		
		/// <summary>
		/// Get any EntidadReferencesTargets links between a given Entidad and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets> GetLinks( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets>();
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets.SourceDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets link in links )
			{
				if ( target.Equals(link.Target) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadReferencesTargets link between a given Entidadand a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets GetLink( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets.SourceDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadReferencesTargets link in links )
			{
				if ( target.Equals(link.Target) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
