//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	/// <summary>
	/// DomainRelationship EntidadHasAtributo
	/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("0423f711-909a-4bc1-a822-21380aa75b3f")]
	public partial class EntidadHasAtributo : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadHasAtributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x0423f711, 0x909a, 0x4bc1, 0xa8, 0x22, 0x21, 0x38, 0x0a, 0xa7, 0x5b, 0x3f);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadHasAtributo link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Atributo to use as the target of the relationship.</param>
		public EntidadHasAtributo(Entidad source, Atributo target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadHasAtributo.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadHasAtributo.AtributoDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasAtributo(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasAtributo(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadHasAtributo(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadHasAtributo(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0xa5e661a0, 0xb086, 0x4603, 0xbc, 0x67, 0xd0, 0xb1, 0x78, 0xaf, 0x4d, 0x72);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo/Entidad.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo/Entidad.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Atributo", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("a5e661a0-b086-4603-bc67-d0b178af4d72")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Atributo
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(Atributo element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(Atributo element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoDomainRoleId, newEntidad);
		}
		#endregion
		#region Atributo domain role code
		
		/// <summary>
		/// Atributo domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoDomainRoleId = new global::System.Guid(0xe444affc, 0x7890, 0x47e5, 0x9c, 0xca, 0x97, 0xec, 0x40, 0xe7, 0x3d, 0xf7);
		
		/// <summary>
		/// DomainRole Atributo
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo.Atributo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo/Atributo.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo/Atributo.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo/Atributo.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("e444affc-7890-47e5-9cca-97ec40e73df7")]
		public virtual Atributo Atributo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Atributo)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Atributo of a Entidad
		/// <summary>
		/// Gets a list of Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Atributo> GetAtributo(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Atributo>, Atributo>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadHasAtributo links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo> GetLinksToAtributo ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo>(entidadInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo.EntidadDomainRoleId);
		}
		#endregion
		#region Atributo link accessor
		/// <summary>
		/// Get the EntidadHasAtributo link to a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo GetLinkToEntidad (global::UPM_IPS.AFTVFRGGBDERAWebBDs.Atributo atributoInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo>(atributoInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo.AtributoDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Atributo not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadHasAtributo instance accessors
		
		/// <summary>
		/// Get any EntidadHasAtributo links between a given Entidad and a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo> GetLinks( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Atributo target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo>();
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadHasAtributo link between a given Entidadand a Atributo.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo GetLink( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Atributo target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadHasAtributo link in links )
			{
				if ( target.Equals(link.Atributo) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	/// <summary>
	/// DomainRelationship TapizERHasComponentes
	/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("e3878240-b859-49c3-b8c0-0680ea7913d7")]
	public partial class TapizERHasComponentes : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// TapizERHasComponentes domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe3878240, 0xb859, 0x49c3, 0xb8, 0xc0, 0x06, 0x80, 0xea, 0x79, 0x13, 0xd7);
	
				
		/// <summary>
		/// Constructor
		/// Creates a TapizERHasComponentes link in the same Partition as the given TapizER
		/// </summary>
		/// <param name="source">TapizER to use as the source of the relationship.</param>
		/// <param name="target">Componentes to use as the target of the relationship.</param>
		public TapizERHasComponentes(TapizER source, Componentes target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(TapizERHasComponentes.TapizERDomainRoleId, source), new DslModeling::RoleAssignment(TapizERHasComponentes.ComponentesDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizERHasComponentes(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizERHasComponentes(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public TapizERHasComponentes(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public TapizERHasComponentes(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region TapizER domain role code
		
		/// <summary>
		/// TapizER domain role Id.
		/// </summary>
		public static readonly global::System.Guid TapizERDomainRoleId = new global::System.Guid(0x309194be, 0x5513, 0x4b2a, 0x85, 0x0d, 0xdc, 0xb8, 0x90, 0xe8, 0x3e, 0x09);
		
		/// <summary>
		/// DomainRole TapizER
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes.TapizER
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes/TapizER.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes/TapizER.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Componentes", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes/TapizER.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("309194be-5513-4b2a-850d-dcb890e83e09")]
		public virtual TapizER TapizER
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (TapizER)DslModeling::DomainRoleInfo.GetRolePlayer(this, TapizERDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, TapizERDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access TapizER of a Componentes
		/// <summary>
		/// Gets TapizER.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static TapizER GetTapizER(Componentes element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ComponentesDomainRoleId) as TapizER;
		}
		
		/// <summary>
		/// Sets TapizER.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetTapizER(Componentes element, TapizER newTapizER)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ComponentesDomainRoleId, newTapizER);
		}
		#endregion
		#region Componentes domain role code
		
		/// <summary>
		/// Componentes domain role Id.
		/// </summary>
		public static readonly global::System.Guid ComponentesDomainRoleId = new global::System.Guid(0x5ed94422, 0xf086, 0x4b26, 0xac, 0x15, 0xed, 0xf3, 0x0a, 0x54, 0x9b, 0x8e);
		
		/// <summary>
		/// DomainRole Componentes
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes.Componentes
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes/Componentes.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes/Componentes.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "TapizER", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes/Componentes.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("5ed94422-f086-4b26-ac15-edf30a549b8e")]
		public virtual Componentes Componentes
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Componentes)DslModeling::DomainRoleInfo.GetRolePlayer(this, ComponentesDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ComponentesDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Componentes of a TapizER
		/// <summary>
		/// Gets a list of Componentes.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Componentes> GetComponentes(TapizER element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Componentes>, Componentes>(element, TapizERDomainRoleId);
		}
		#endregion
		#region TapizER link accessor
		/// <summary>
		/// Get the list of TapizERHasComponentes links to a TapizER.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes> GetLinksToComponentes ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizER tapizERInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes>(tapizERInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes.TapizERDomainRoleId);
		}
		#endregion
		#region Componentes link accessor
		/// <summary>
		/// Get the TapizERHasComponentes link to a Componentes.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes GetLinkToTapizER (global::UPM_IPS.AFTVFRGGBDERAWebBDs.Componentes componentesInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes>(componentesInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes.ComponentesDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Componentes not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region TapizERHasComponentes instance accessors
		
		/// <summary>
		/// Get any TapizERHasComponentes links between a given TapizER and a Componentes.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes> GetLinks( global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizER source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Componentes target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes>();
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes.TapizERDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes link in links )
			{
				if ( target.Equals(link.Componentes) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one TapizERHasComponentes link between a given TapizERand a Componentes.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes GetLink( global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizER source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Componentes target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes.TapizERDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.TapizERHasComponentes link in links )
			{
				if ( target.Equals(link.Componentes) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	/// <summary>
	/// DomainRelationship EntidadOrigen
	/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("dcef7926-8070-49bf-9e4a-0c274f3c3d11")]
	public partial class EntidadOrigen : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadOrigen domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xdcef7926, 0x8070, 0x49bf, 0x9e, 0x4a, 0x0c, 0x27, 0x4f, 0x3c, 0x3d, 0x11);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadOrigen link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public EntidadOrigen(Entidad source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadOrigen.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadOrigen.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadOrigen(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadOrigen(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadOrigen(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadOrigen(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x013130c3, 0x6b77, 0x4795, 0x8c, 0x2f, 0x37, 0x42, 0xa2, 0x6e, 0x7a, 0xab);
		
		/// <summary>
		/// DomainRole Entidad
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen/Entidad.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen/Entidad.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacion", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("013130c3-6b77-4795-8c2f-3742a26e7aab")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Relacion
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(Relacion element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, RelacionDomainRoleId);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x400e8e21, 0x93c6, 0x4035, 0x88, 0xd7, 0x0f, 0x52, 0x95, 0x48, 0xc1, 0xf8);
		
		/// <summary>
		/// DomainRole Relacion
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen/Relacion.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen/Relacion.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen/Relacion.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("400e8e21-93c6-4035-88d7-0f529548c1f8")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacion of a Entidad
		/// <summary>
		/// Gets a list of Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Relacion> GetRelacion(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Cardinalidad domain property code
		
		/// <summary>
		/// Cardinalidad domain property Id.
		/// </summary>
		public static readonly global::System.Guid CardinalidadDomainPropertyId = new global::System.Guid(0xcc342bb7, 0xbb5d, 0x4e2c, 0x89, 0x41, 0x4e, 0xfb, 0xe5, 0x71, 0x27, 0xb6);
		
		/// <summary>
		/// Storage for Cardinalidad
		/// </summary>
		private global::System.String cardinalidadPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Cardinalidad domain property.
		/// Description for UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.Cardinalidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen/Cardinalidad.DisplayName", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen/Cardinalidad.Description", typeof(global::UPM_IPS.AFTVFRGGBDERAWebBDs.AFTVFRGGBDERAWebBDsDomainModel), "UPM_IPS.AFTVFRGGBDERAWebBDs.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("cc342bb7-bb5d-4e2c-8941-4efbe57127b6")]
		public global::System.String Cardinalidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cardinalidadPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				CardinalidadPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the EntidadOrigen.Cardinalidad domain property.
		/// </summary>
		internal sealed partial class CardinalidadPropertyHandler : DslModeling::DomainPropertyValueHandler<EntidadOrigen, global::System.String>
		{
			private CardinalidadPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the EntidadOrigen.Cardinalidad domain property value handler.
			/// </summary>
			public static readonly CardinalidadPropertyHandler Instance = new CardinalidadPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the EntidadOrigen.Cardinalidad domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return CardinalidadDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(EntidadOrigen element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cardinalidadPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(EntidadOrigen element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cardinalidadPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadOrigen links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen> GetLinksToRelacion ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen>(entidadInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.EntidadDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the list of EntidadOrigen links to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen> GetLinksToEntidad ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Relacion relacionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen>(relacionInstance, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.RelacionDomainRoleId);
		}
		#endregion
		#region EntidadOrigen instance accessors
		
		/// <summary>
		/// Get any EntidadOrigen links between a given Entidad and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen> GetLinks( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Relacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen>();
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadOrigen link between a given Entidadand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen GetLink( global::UPM_IPS.AFTVFRGGBDERAWebBDs.Entidad source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.Relacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen>(source, global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.AFTVFRGGBDERAWebBDs.EntidadOrigen link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
