//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "AFTVFRGGB_DSLDERAWebBDs";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"AFTVFRGGBDERAWebBDs";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID AFTVFRGGBDERAWebBDsDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AFTVFRGGBDERAWebBDsCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID AFTVFRGGBDERAWebBDsExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AFTVFRGGBDERAWebBDsCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewAFTVFRGGBDERAWebBDsExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AFTVFRGGBDERAWebBDsCommandSetId), 0x0001);
	
		// Package identifier
		public const string AFTVFRGGBDERAWebBDsPackageId = "b693abf6-9f5c-4534-98c8-969450af4f04";
		
		// Editor factory identifier
		public const string AFTVFRGGBDERAWebBDsEditorFactoryId = "6d08c705-ca5f-47c9-bcd8-537592d2c7ab";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string AFTVFRGGBDERAWebBDsModelExplorerToolWindowId = "5b9f2d15-3416-4e35-8a51-f359d48ff9f9";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string AFTVFRGGBDERAWebBDsCommandSetId = "5baeca28-fc05-4423-9222-5c2af626998c";
	}
}