//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "AFTVFRGGB_DSLDERAWebBDs";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"AFTVFRGGBDERAWebBDs";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID AFTVFRGGBDERAWebBDsDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AFTVFRGGBDERAWebBDsCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID AFTVFRGGBDERAWebBDsExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AFTVFRGGBDERAWebBDsCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewAFTVFRGGBDERAWebBDsExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AFTVFRGGBDERAWebBDsCommandSetId), 0x0001);
	
		// Package identifier
		public const string AFTVFRGGBDERAWebBDsPackageId = "dea5e051-517d-47b1-88d4-85a4f7ef9a2e";
		
		// Editor factory identifier
		public const string AFTVFRGGBDERAWebBDsEditorFactoryId = "7c7b976f-fe00-487d-9c41-0cd5205722e6";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string AFTVFRGGBDERAWebBDsModelExplorerToolWindowId = "ce5dcc33-f03c-48ce-9f7d-8a558fe259a9";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.AFTVFRGGBDERAWebBDs
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string AFTVFRGGBDERAWebBDsCommandSetId = "48829d9d-cc1a-4802-a3fd-edc58e941e7f";
	}
}